### PR TITLE
NeoPixel fill is not on V1

### PR DESCRIPTION
**Pull request by microbit-matt-hillsdon**
Closes https://github.com/microbit-foundation/micropython-microbit-stubs/issues/92

### CODE REVIEW

**Comment by microbit-matt-hillsdon** [comment]
I'll try to address translations here with some manual work.

**Review by microbit-robert — APPROVED** [review]
LGTM.

**Comment by microbit-matt-hillsdon** [comment]
image

I've done this on import to Crowdin so need to make manual checks/updates to the kept strings across the supported languages.

**Comment by microbit-matt-hillsdon** [comment]
I've since made a best effort attempt to keep translations in Crowdin. I've dropped proofreading status in non-trivial cases so my work gets some review.

**Pull request merged**
